openapi: 3.0.0
info:
  title: SosAlerta API
  version: 1.0.0
  description: Documentação das rotas de Usuários, Alertas e Clima
servers:
  - url: /
paths:
  /usuarios/register:
    post:
      summary: Registra um usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '201':
          description: Usuário criado
        '400':
          description: Erro de validação
  /usuarios/login:
    post:
      summary: Faz login e retorna um JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        '200':
          description: Sessão criada
        '401':
          description: Credenciais inválidas
  /clima:
    get:
      summary: Busca dados de clima e alertas pela geolocalização
      parameters:
        - in: query
          name: lat
          schema:
            type: number
          required: true
        - in: query
          name: lon
          schema:
            type: number
          required: true
      responses:
        '200':
          description: Dados de clima e alertas
  /alertas:
    get:
      summary: Lista todos os alertas salvos (protegido por JWT)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de alertas
components:
  schemas:
    UserCredentials:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
